export const REFRESH_PROJECTS = 'REFRESH_PROJECTS';
export const PUT_PROJECT = 'PUT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
