export const DI_PROJECT_URI_NAME = 'DI_PROJECT_URI_NAME';
export const DI_SERVER_URL_NAME = 'DI_SERVER_URL_NAME';
export const DI_HTTP_SERVICE_NAME = 'DI_HTTP_SERVICE_NAME';
export const DI_ANIMATION_WAITTIME_MS_NAME = "DI_ANIMATION_WAITTIME_MS_NAME";
