export const DI_PROJECT_URI = 'DI_PROJECT_URI';
export const DI_SERVER_URL = 'DI_SERVER_URL';
export const DI_HTTP_SERVICE = 'DI_HTTP_SERVICE';
export const DI_ANIMATION_WAITTIME_MS = "DI_ANIMATION_WAITTIME_MS";
export const DI_EVENT_HUB = "DI_EVENT_HUB";
